import Head from "next/head";
import HFLayout from "../../../layouts/HFLayout";
import Header from "../../../components/common/Header";
import PagesLayout from "../../../layouts/PagesLayout";
import PageLayout from "../../../layouts/PageLayout";
import Footer from "../../../components/common/Footer";
import FirstStep from "../../../components/auth/registration/FirstStep";
import CustomerReg from "../../../components/auth/registration/CustomerReg";

export default function CustomerRegPage() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HFLayout>
        <Header />

        <PagesLayout>
          <PageLayout>
            <CustomerReg />
          </PageLayout>
        </PagesLayout>
        <Footer />
      </HFLayout>
    </>
  );
}
